matplotlib
pandas
numpy
requests
asgiref==3.3.1
django==3.1.5
imbalanced-learn==0.6.2
joblib==0.14.1
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
lightgbm==2.3.1
scikit-learn==0.22.2.post1
sqlparse==0.4.1
xgboost==1.1.1
mygene
