# Generated by Django 3.1.5 on 2021-01-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponsol2web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='solubility',
            field=models.TextField(choices=[('-', 'decrease'), ('no', 'no-change'), ('+', 'increase')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
