# Generated by Django 2.2.5 on 2021-02-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponsol2web', '0002_auto_20210123_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='solubility',
            field=models.TextField(choices=[('-1', 'decrease'), ('0', 'no-change'), ('1', 'increase')], max_length=20),
        ),
    ]
