# Generated by Django 2.2.5 on 2021-02-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponsol2web', '0003_auto_20210203_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='seq_id',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='seq_id_type',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
