# Generated by Django 2.2.5 on 2021-02-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponsol2web', '0006_auto_20210220_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='solubility',
            field=models.TextField(choices=[('-1', 'decrease'), ('0', 'no-change'), ('1', 'increase')], max_length=20, null=True),
        ),
    ]
