# Generated by Django 2.2.5 on 2021-02-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponsol2web', '0007_auto_20210220_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='error_msg',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.TextField(default='running', max_length=20, null=True),
        ),
    ]
