# Generated by Django 3.1.5 on 2021-04-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponsol2web', '0008_auto_20210220_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='input_type',
            field=models.TextField(choices=[('id', 'ID'), ('seq', 'Sequence')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='seq_id_type',
            field=models.TextField(choices=[('uniprot id', 'UniProtKB/Swiss-Prot ID'), ('gi', 'Entrez Gene ID'), ('ensembl id', 'Ensembl ID'), ('seq', 'Only Sequence')], max_length=20, null=True),
        ),
    ]
