# Generated by Django 3.1.5 on 2021-04-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponsol2web', '0011_auto_20210427_1502'),
        ('ponsol2web', '0009_task_user'),
    ]

    operations = [
    ]
